version: '3.3'

services:
  log_server:
    container_name: log_server
    build:
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - '3333:3333'
    networks:
      - log_network
    depends_on:
      - mysql-log

  mysql-log:
    container_name: mysql-log
    image: mysql:8.1.0
    ports:
      - '3390:3306'
    environment:
      - MYSQL_DATABASE=logteste
      - MYSQL_ROOT_PASSWORD=nf231
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    networks:
      - mk_network
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  log_network:
    driver: bridge